### ISSUE TITLE
请问下，前端什么时候放出来？

### ISSUE THREAD

**Issue by hot588** [lgcgo/GaAdmin#1]
这个goframe，你弄的非常不错，我一直在关注！

前端是不是就直接是 ant pro V5 最佳实践？

**Comment by lgcgo** [comment]
> 这个goframe，你弄的非常不错，我一直在关注！
> 
> 前端是不是就直接是 ant pro V5 最佳实践？

你好！是的，前端就是Ant pro v5的最佳实践，前端估计得下个月初才能补上来。
